// backend/cuda_codegen.cpp - CUDA 代码生成器实现
// 将 TensorIR (claw::tensorir) + Schedule 转换为 CUDA C++ 代码

#include "cuda_codegen.h"
#include <algorithm>
#include <numeric>
#include <cmath>

namespace claw {
namespace backend {

// ============================================================================
// CUDAKernelCodegen 实现
// ============================================================================

CUDAKernelCodegen::CUDAKernelCodegen(const CUDACodegenConfig& config)
    : config_(config), indent_level_(0) {}

std::string CUDAKernelCodegen::generate_kernel(
    const tensorir::TensorOp& op,
    const tensorir::Schedule& schedule) {
    
    code_.str("");
    code_.clear();
    thread_mappings_.clear();
    shared_caches_.clear();
    generated_loops_.clear();
    kernel_meta_ = CUDAKernelMeta();
    indent_level_ = 0;
    
    kernel_meta_.kernel_name = op.name + "_cuda_kernel";
    
    analyze_shared_memory(op, schedule);
    compute_thread_mappings(op, schedule);
    generate_kernel_signature(op);
    
    if (config_.use_shared_memory && !shared_caches_.empty()) {
        generate_shared_memory_declarations();
    }
    
    generate_loop_nest(op, schedule);
    
    decrease_indent();
    emit_line("}");
    
    return code_.str();
}

void CUDAKernelCodegen::emit_line(const std::string& line) {
    emit_indent();
    code_ << line << "\n";
}

void CUDAKernelCodegen::emit_indent() {
    for (int i = 0; i < indent_level_; ++i) {
        code_ << "  ";
    }
}

void CUDAKernelCodegen::generate_kernel_signature(const tensorir::TensorOp& op) {
    emit_line("// CUDA Kernel: " + op.name);
    emit_line("// Generated by Claw Compiler CUDA Backend");
    emit_line("");
    
    std::string sig = "__global__ void " + kernel_meta_.kernel_name + "(";
    
    std::vector<std::string> params;
    for (const auto* buf : op.inputs) {
        if (buf) {
            std::string type = get_element_type(buf);
            params.push_back(type + "* __restrict__ " + buf->name);
            kernel_meta_.arg_names.push_back(buf->name);
            kernel_meta_.arg_types.push_back(type + "*");
            std::vector<int64_t> shape;
            for (const auto& d : buf->shape) {
                if (std::holds_alternative<int64_t>(d)) {
                    shape.push_back(std::get<int64_t>(d));
                } else {
                    shape.push_back(1024);
                }
            }
            kernel_meta_.arg_shapes.push_back(shape);
        }
    }
    for (const auto* buf : op.outputs) {
        if (buf) {
            bool already_added = false;
            for (const auto* in : op.inputs) {
                if (in && in->name == buf->name) {
                    already_added = true;
                    break;
                }
            }
            if (!already_added) {
                std::string type = get_element_type(buf);
                params.push_back(type + "* __restrict__ " + buf->name);
                kernel_meta_.arg_names.push_back(buf->name);
                kernel_meta_.arg_types.push_back(type + "*");
                std::vector<int64_t> shape;
                for (const auto& d : buf->shape) {
                    if (std::holds_alternative<int64_t>(d)) {
                        shape.push_back(std::get<int64_t>(d));
                    } else {
                        shape.push_back(1024);
                    }
                }
                kernel_meta_.arg_shapes.push_back(shape);
            }
        }
    }
    
    for (size_t i = 0; i < params.size(); ++i) {
        if (i > 0) sig += ", ";
        sig += params[i];
    }
    sig += ") {";
    
    emit_line(sig);
    increase_indent();
}

void CUDAKernelCodegen::generate_shared_memory_declarations() {
    emit_line("// Shared memory declarations");
    for (const auto& cache : shared_caches_) {
        std::string decl = "__shared__ " + cache.element_type + " " + cache.shared_var_name;
        if (!cache.tile_shape.empty()) {
            decl += "[" + std::to_string(compute_product(cache.tile_shape)) + "]";
        }
        decl += ";  // " + std::to_string(cache.total_size_bytes) + " bytes";
        emit_line(decl);
    }
    emit_line("");
}

void CUDAKernelCodegen::generate_loop_nest(
    const tensorir::TensorOp& op,
    const tensorir::Schedule& schedule) {
    (void)schedule;
    
    if (!op.iter_vars.empty()) {
        emit_line("// Thread indexing");
    }
    
    // 生成映射到 CUDA 线程的循环
    for (const auto* iter : op.iter_vars) {
        if (!iter) continue;
        auto it = thread_mappings_.find(iter->name);
        if (it != thread_mappings_.end()) {
            int64_t extent = get_iter_extent(iter);
            generate_loop(iter->name, extent, it->second);
        }
    }
    
    // 生成串行循环
    for (const auto* iter : op.iter_vars) {
        if (!iter) continue;
        auto it = thread_mappings_.find(iter->name);
        if (it == thread_mappings_.end() || it->second.mapping_type == "serial") {
            ThreadMapping mapping;
            mapping.iter_name = iter->name;
            mapping.mapping_type = "serial";
            int64_t extent = get_iter_extent(iter);
            generate_loop(iter->name, extent, mapping);
        }
    }
    
    // 生成循环体
    generate_loop_body(op);
    
    // 关闭循环
    for (size_t i = 0; i < generated_loops_.size(); ++i) {
        decrease_indent();
        emit_line("}");
    }
}

void CUDAKernelCodegen::generate_loop(const std::string& iter_name,
                                       int64_t extent,
                                       const ThreadMapping& mapping) {
    if (generated_loops_.count(iter_name)) {
        return;
    }
    generated_loops_.insert(iter_name);
    
    if (mapping.mapping_type.find("blockIdx") != std::string::npos) {
        std::string axis = mapping.mapping_type.substr(mapping.mapping_type.find(".") + 1);
        emit_line("int " + iter_name + " = blockIdx." + axis + " * " + 
                  std::to_string(mapping.tile_size) + " + threadIdx." + axis + ";");
        if (extent > 0) {
            emit_line("if (" + iter_name + " >= " + std::to_string(extent) + ") return;");
        }
    } else if (mapping.mapping_type.find("threadIdx") != std::string::npos) {
        std::string axis = mapping.mapping_type.substr(mapping.mapping_type.find(".") + 1);
        emit_line("int " + iter_name + " = threadIdx." + axis + ";");
        if (extent > 0) {
            emit_line("if (" + iter_name + " >= " + std::to_string(extent) + ") return;");
        }
    } else {
        std::string loop_header = "for (int " + iter_name + " = 0; ";
        loop_header += iter_name + " < " + std::to_string(extent) + "; ";
        loop_header += "++" + iter_name + ") {";
        emit_line(loop_header);
        increase_indent();
    }
    
    if (mapping.vectorized && mapping.vector_width > 1) {
        emit_line("// Vectorized: width=" + std::to_string(mapping.vector_width));
    }
    if (mapping.unroll_factor > 1) {
        emit_line("#pragma unroll " + std::to_string(mapping.unroll_factor));
    }
}

void CUDAKernelCodegen::generate_loop_body(const tensorir::TensorOp& op) {
    generate_node(op);
}

void CUDAKernelCodegen::generate_node(const tensorir::TensorOp& op) {
    switch (op.kind) {
        case tensorir::TensorOp::OpKind::Matmul: {
            auto* matmul = dynamic_cast<const tensorir::MatmulOp*>(&op);
            if (matmul) generate_matmul(*matmul);
            break;
        }
        case tensorir::TensorOp::OpKind::Conv2d: {
            auto* conv = dynamic_cast<const tensorir::Conv2dOp*>(&op);
            if (conv) generate_conv2d(*conv);
            break;
        }
        case tensorir::TensorOp::OpKind::Reduce: {
            auto* red = dynamic_cast<const tensorir::ReduceOp*>(&op);
            if (red) generate_reduction(*red);
            break;
        }
        case tensorir::TensorOp::OpKind::Compute: {
            auto* compute = dynamic_cast<const tensorir::ComputeOp*>(&op);
            if (compute) generate_compute(*compute);
            break;
        }
        default:
            emit_line("// Unsupported op kind: " + std::to_string(static_cast<int>(op.kind)));
            break;
    }
}

void CUDAKernelCodegen::generate_matmul(const tensorir::MatmulOp& op) {
    emit_line("// Matmul operation");
    
    if (op.inputs.size() >= 2 && op.outputs.size() >= 1) {
        std::string a = op.inputs[0] ? op.inputs[0]->name : "A";
        std::string b = op.inputs[1] ? op.inputs[1]->name : "B";
        std::string c = op.outputs[0] ? op.outputs[0]->name : "C";
        
        emit_line(c + "[0] += " + a + "[0] * " + b + "[0];  // Simplified matmul");
    }
}

void CUDAKernelCodegen::generate_conv2d(const tensorir::Conv2dOp& op) {
    emit_line("// Conv2D operation");
    emit_line("// stride=[" + std::to_string(op.strides[0]) + "," + 
              std::to_string(op.strides[1]) + "]");
    emit_line("// padding=[" + std::to_string(op.padding[0]) + "," + 
              std::to_string(op.padding[1]) + "]");
    
    if (!op.outputs.empty() && op.outputs[0]) {
        emit_line(op.outputs[0]->name + "[0] = 0.0f;  // Placeholder");
    }
}

void CUDAKernelCodegen::generate_reduction(const tensorir::ReduceOp& op) {
    emit_line("// Reduction operation");
    
    std::string op_str;
    switch (op.reduce_type) {
        case tensorir::ReduceOp::ReduceType::Sum: op_str = " += "; break;
        case tensorir::ReduceOp::ReduceType::Mean: op_str = " += "; break;
        case tensorir::ReduceOp::ReduceType::Max: op_str = " = max("; break;
        case tensorir::ReduceOp::ReduceType::Min: op_str = " = min("; break;
        case tensorir::ReduceOp::ReduceType::Prod: op_str = " *= "; break;
    }
    
    if (!op.outputs.empty() && op.outputs[0] && !op.inputs.empty() && op.inputs[0]) {
        std::string dst = op.outputs[0]->name;
        std::string src = op.inputs[0]->name;
        
        if (op.reduce_type == tensorir::ReduceOp::ReduceType::Max ||
            op.reduce_type == tensorir::ReduceOp::ReduceType::Min) {
            emit_line(dst + "[0]" + op_str + dst + "[0], " + src + "[0]);");
        } else {
            emit_line(dst + "[0]" + op_str + src + "[0];");
        }
    }
}

void CUDAKernelCodegen::generate_compute(const tensorir::ComputeOp& op) {
    emit_line("// Compute operation: " + op.body_expr);
    if (!op.outputs.empty() && op.outputs[0]) {
        emit_line(op.outputs[0]->name + "[0] = 0.0f;  // Placeholder");
    }
}

std::string CUDAKernelCodegen::generate_buffer_access(const tensorir::BufferAccess& access) {
    std::string result = access.buffer->name + "[";
    for (size_t i = 0; i < access.indices.size(); ++i) {
        if (i > 0) result += " + ";
        result += generate_index_expr(access.indices[i]);
    }
    result += "]";
    return result;
}

std::string CUDAKernelCodegen::generate_index_expr(const std::variant<tensorir::IterVar*, int64_t>& idx) {
    if (std::holds_alternative<int64_t>(idx)) {
        return std::to_string(std::get<int64_t>(idx));
    } else if (std::holds_alternative<tensorir::IterVar*>(idx)) {
        auto* iter = std::get<tensorir::IterVar*>(idx);
        return iter ? iter->name : "0";
    }
    return "0";
}

void CUDAKernelCodegen::compute_thread_mappings(
    const tensorir::TensorOp& op,
    const tensorir::Schedule& schedule) {
    
    for (const auto& prim : schedule.prims) {
        switch (prim.type) {
            case tensorir::Schedule::PrimType::Bind: {
                if (!prim.iter_names.empty()) {
                    ThreadMapping mapping;
                    mapping.iter_name = prim.iter_names[0];
                    if (std::holds_alternative<std::string>(prim.params)) {
                        mapping.mapping_type = std::get<std::string>(prim.params);
                    }
                    thread_mappings_[mapping.iter_name] = mapping;
                }
                break;
            }
            case tensorir::Schedule::PrimType::Tile: {
                if (std::holds_alternative<std::vector<int64_t>>(prim.params)) {
                    auto sizes = std::get<std::vector<int64_t>>(prim.params);
                    if (!sizes.empty()) {
                        for (auto& [name, mapping] : thread_mappings_) {
                            mapping.tile_size = static_cast<int>(sizes[0]);
                        }
                    }
                }
                break;
            }
            case tensorir::Schedule::PrimType::Vectorize: {
                if (!prim.iter_names.empty()) {
                    ThreadMapping mapping;
                    mapping.iter_name = prim.iter_names[0];
                    mapping.vectorized = true;
                    mapping.vector_width = 4;
                    thread_mappings_[mapping.iter_name] = mapping;
                }
                break;
            }
            case tensorir::Schedule::PrimType::Unroll: {
                if (!prim.iter_names.empty()) {
                    ThreadMapping mapping;
                    mapping.iter_name = prim.iter_names[0];
                    mapping.unroll_factor = 4;
                    thread_mappings_[mapping.iter_name] = mapping;
                }
                break;
            }
            default:
                break;
        }
    }
    
    // 默认映射
    if (thread_mappings_.empty() && !op.iter_vars.empty()) {
        if (op.iter_vars[0]) {
            ThreadMapping block_mapping;
            block_mapping.iter_name = op.iter_vars[0]->name;
            block_mapping.mapping_type = "blockIdx.x";
            block_mapping.tile_size = 256;
            thread_mappings_[block_mapping.iter_name] = block_mapping;
        }
        
        if (op.iter_vars.size() > 1 && op.iter_vars[1]) {
            ThreadMapping thread_mapping;
            thread_mapping.iter_name = op.iter_vars[1]->name;
            thread_mapping.mapping_type = "threadIdx.x";
            thread_mapping.tile_size = 256;
            thread_mappings_[thread_mapping.iter_name] = thread_mapping;
        }
    }
    
    kernel_meta_.block_dim_x = 256;
    kernel_meta_.block_dim_y = 1;
    kernel_meta_.block_dim_z = 1;
    kernel_meta_.grid_dim_x = 1;
    kernel_meta_.grid_dim_y = 1;
    kernel_meta_.grid_dim_z = 1;
    
    for (const auto& [iter, mapping] : thread_mappings_) {
        if (mapping.mapping_type == "blockIdx.x") {
            kernel_meta_.grid_dim_x = std::max(1, (mapping.tile_size + kernel_meta_.block_dim_x - 1) / kernel_meta_.block_dim_x);
        } else if (mapping.mapping_type == "blockIdx.y") {
            kernel_meta_.grid_dim_y = mapping.tile_size;
        } else if (mapping.mapping_type == "threadIdx.x") {
            kernel_meta_.block_dim_x = std::min(mapping.tile_size, config_.max_threads_per_block);
        }
    }
}

void CUDAKernelCodegen::analyze_shared_memory(
    const tensorir::TensorOp& op,
    const tensorir::Schedule& schedule) {
    (void)op;
    
    if (!config_.use_shared_memory) {
        return;
    }
    
    for (const auto& prim : schedule.prims) {
        if (prim.type == tensorir::Schedule::PrimType::CacheRead ||
            prim.type == tensorir::Schedule::PrimType::CacheWrite) {
            if (!prim.iter_names.empty()) {
                SharedMemoryCache cache;
                cache.buffer_name = prim.iter_names[0];
                cache.shared_var_name = cache.buffer_name + "_shared";
                cache.tile_shape = {16, 16};
                cache.element_type = "float";
                cache.total_size_bytes = compute_product(cache.tile_shape) * sizeof(float);
                
                if (cache.total_size_bytes <= static_cast<size_t>(config_.max_shared_memory_per_block)) {
                    shared_caches_.push_back(cache);
                    kernel_meta_.shared_memory_size += static_cast<int>(cache.total_size_bytes);
                }
            }
        }
    }
}

std::string CUDAKernelCodegen::get_element_type(const tensorir::Buffer* buf) const {
    if (!buf) return "float";
    if (buf->elem_type == "f32") return "float";
    if (buf->elem_type == "f64") return "double";
    if (buf->elem_type == "i32") return "int";
    if (buf->elem_type == "i64") return "int64_t";
    if (buf->elem_type == "u32") return "uint32_t";
    if (buf->elem_type == "u8") return "uint8_t";
    return "float";
}

int64_t CUDAKernelCodegen::compute_product(const std::vector<int64_t>& dims) const {
    if (dims.empty()) return 1;
    return std::accumulate(dims.begin(), dims.end(), 1LL, std::multiplies<int64_t>());
}

int64_t CUDAKernelCodegen::get_iter_extent(const tensorir::IterVar* iter) const {
    if (!iter) return 1024;
    if (std::holds_alternative<int64_t>(iter->range.extent)) {
        return std::get<int64_t>(iter->range.extent);
    }
    return 1024;
}

// ============================================================================
// CUDAHostCodegen 实现
// ============================================================================

CUDAHostCodegen::CUDAHostCodegen(const CUDACodegenConfig& config)
    : config_(config), indent_level_(0) {}

std::string CUDAHostCodegen::generate_host_wrapper(
    const tensorir::TensorOp& op,
    const CUDAKernelMeta& kernel_meta) {
    
    code_.str("");
    code_.clear();
    indent_level_ = 0;
    
    emit_line("// Host wrapper for " + op.name);
    emit_line("extern \"C\" void " + op.name + "_cuda(");
    increase_indent();
    
    std::vector<std::string> all_bufs;
    for (const auto* buf : op.inputs) {
        if (buf) {
            std::string line = get_element_type(buf) + "* " + buf->name;
            line += ",";
            emit_line(line);
            all_bufs.push_back(buf->name);
        }
    }
    for (const auto* buf : op.outputs) {
        if (buf) {
            bool already = false;
            for (const auto* in : op.inputs) {
                if (in && in->name == buf->name) {
                    already = true;
                    break;
                }
            }
            if (!already) {
                std::string line = get_element_type(buf) + "* " + buf->name;
                line += ",";
                emit_line(line);
                all_bufs.push_back(buf->name);
            }
        }
    }
    decrease_indent();
    emit_line(") {");
    increase_indent();
    
    emit_line("// Device memory allocation");
    for (const auto& name : all_bufs) {
        generate_device_alloc(name, "float", 1024 * 1024 * sizeof(float));
    }
    emit_line("");
    
    emit_line("// Copy data to device");
    for (const auto& name : all_bufs) {
        generate_memcpy_h2d(name, "d_" + name, 1024 * 1024 * sizeof(float));
    }
    emit_line("");
    
    emit_line("// Launch kernel");
    std::vector<std::string> device_args;
    for (const auto& name : all_bufs) {
        device_args.push_back("d_" + name);
    }
    generate_kernel_launch(kernel_meta, device_args);
    emit_line("");
    
    emit_line("// Copy result back to host");
    if (!all_bufs.empty()) {
        generate_memcpy_d2h("d_" + all_bufs[0], all_bufs[0], 1024 * 1024 * sizeof(float));
    }
    emit_line("");
    
    emit_line("// Free device memory");
    for (const auto& name : all_bufs) {
        generate_device_free("d_" + name);
    }
    
    decrease_indent();
    emit_line("}");
    emit_line("");
    
    return code_.str();
}

std::string CUDAHostCodegen::generate_memory_management(const tensorir::TensorOp& op) {
    (void)op;
    std::stringstream local_code;
    int local_indent = 0;
    
    auto emit = [&](const std::string& line) {
        for (int i = 0; i < local_indent; ++i) {
            local_code << "  ";
        }
        local_code << line << "\n";
    };
    
    emit("// Memory management utilities");
    emit("template<typename T>");
    emit("T* cuda_alloc(size_t count) {");
    local_indent++;
    emit("T* ptr = nullptr;");
    emit("cudaMalloc(&ptr, count * sizeof(T));");
    emit("return ptr;");
    local_indent--;
    emit("}");
    emit("");
    
    emit("template<typename T>");
    emit("void cuda_free(T* ptr) {");
    local_indent++;
    emit("cudaFree(ptr);");
    local_indent--;
    emit("}");
    emit("");
    
    return local_code.str();
}

std::string CUDAHostCodegen::generate_host_module(
    const tensorir::TensorIRModule& module,
    const std::vector<CUDAKernelMeta>& kernel_metas) {
    
    code_.str("");
    code_.clear();
    indent_level_ = 0;
    
    emit_line("#include <cuda_runtime.h>");
    emit_line("#include <cuda_runtime_api.h>");
    emit_line("#include <device_launch_parameters.h>");
    emit_line("#include <cstdio>");
    emit_line("#include <cstdlib>");
    emit_line("");
    
    generate_error_check_macro();
    emit_line("");
    
    code_ << generate_memory_management(tensorir::ComputeOp(""));
    
    for (const auto& meta : kernel_metas) {
        emit_line("__global__ void " + meta.kernel_name + "(");
        increase_indent();
        for (size_t i = 0; i < meta.arg_names.size(); ++i) {
            std::string line = meta.arg_types[i] + " " + meta.arg_names[i];
            if (i < meta.arg_names.size() - 1) line += ",";
            emit_line(line);
        }
        decrease_indent();
        emit_line(");");
    }
    emit_line("");
    
    return code_.str();
}

void CUDAHostCodegen::emit_line(const std::string& line) {
    emit_indent();
    code_ << line << "\n";
}

void CUDAHostCodegen::emit_indent() {
    for (int i = 0; i < indent_level_; ++i) {
        code_ << "  ";
    }
}

void CUDAHostCodegen::generate_error_check_macro() {
    emit_line("#define CUDA_CHECK(call) \\");
    emit_line("  do { \\");
    emit_line("    cudaError_t err = call; \\");
    emit_line("    if (err != cudaSuccess) { \\");
    emit_line("      fprintf(stderr, \"CUDA error at %s:%d: %s\\n\", \\");
    emit_line("              __FILE__, __LINE__, cudaGetErrorString(err)); \\");
    emit_line("      exit(EXIT_FAILURE); \\");
    emit_line("    } \\");
    emit_line("  } while(0)");
}

void CUDAHostCodegen::generate_device_alloc(const std::string& name,
                                              const std::string& type,
                                              size_t size) {
    (void)type;
    emit_line("float* d_" + name + " = nullptr;");
    emit_line("CUDA_CHECK(cudaMalloc(&d_" + name + ", " + std::to_string(size) + "));");
}

void CUDAHostCodegen::generate_memcpy_h2d(const std::string& host_ptr,
                                            const std::string& device_ptr,
                                            size_t size) {
    emit_line("CUDA_CHECK(cudaMemcpy(" + device_ptr + ", " + host_ptr + ", " +
              std::to_string(size) + ", cudaMemcpyHostToDevice));");
}

void CUDAHostCodegen::generate_memcpy_d2h(const std::string& device_ptr,
                                            const std::string& host_ptr,
                                            size_t size) {
    emit_line("CUDA_CHECK(cudaMemcpy(" + host_ptr + ", " + device_ptr + ", " +
              std::to_string(size) + ", cudaMemcpyDeviceToHost));");
}

void CUDAHostCodegen::generate_kernel_launch(const CUDAKernelMeta& meta,
                                              const std::vector<std::string>& arg_names) {
    emit_line("dim3 block(" + std::to_string(meta.block_dim_x) + ", " +
              std::to_string(meta.block_dim_y) + ", " +
              std::to_string(meta.block_dim_z) + ");");
    emit_line("dim3 grid(" + std::to_string(meta.grid_dim_x) + ", " +
              std::to_string(meta.grid_dim_y) + ", " +
              std::to_string(meta.grid_dim_z) + ");");
    
    if (meta.shared_memory_size > 0) {
        emit_line("size_t shared_mem = " + std::to_string(meta.shared_memory_size) + ";");
    }
    
    std::string launch = meta.kernel_name + "<<<grid, block";
    if (meta.shared_memory_size > 0) {
        launch += ", shared_mem";
    }
    launch += ">>>(";
    
    for (size_t i = 0; i < arg_names.size(); ++i) {
        if (i > 0) launch += ", ";
        launch += arg_names[i];
    }
    launch += ");";
    
    emit_line(launch);
    emit_line("CUDA_CHECK(cudaDeviceSynchronize());");
}

void CUDAHostCodegen::generate_device_free(const std::string& name) {
    emit_line("CUDA_CHECK(cudaFree(" + name + "));");
}

std::string CUDAHostCodegen::get_element_type(const tensorir::Buffer* buf) const {
    if (!buf) return "float";
    if (buf->elem_type == "f32") return "float";
    if (buf->elem_type == "f64") return "double";
    if (buf->elem_type == "i32") return "int";
    if (buf->elem_type == "i64") return "int64_t";
    if (buf->elem_type == "u32") return "uint32_t";
    if (buf->elem_type == "u8") return "uint8_t";
    return "float";
}

// ============================================================================
// CUDACodeGenerator 实现
// ============================================================================

CUDACodeGenerator::CUDACodeGenerator(const CUDACodegenConfig& config)
    : config_(config), kernel_codegen_(config), host_codegen_(config) {}

std::string CUDACodeGenerator::generate_module(
    const tensorir::TensorIRModule& module) {
    
    std::string result;
    kernel_metas_.clear();
    
    result += host_codegen_.generate_host_module(module, {});
    
    for (const auto& op : module.operations) {
        if (op) {
            auto sched_it = module.schedules.find(op.get());
            tensorir::Schedule default_sched(op.get());
            const tensorir::Schedule* sched = &default_sched;
            if (sched_it != module.schedules.end() && sched_it->second) {
                sched = sched_it->second.get();
            }
            
            std::string kernel = kernel_codegen_.generate_kernel(*op, *sched);
            result += kernel;
            result += "\n";
            kernel_metas_.push_back(kernel_codegen_.get_kernel_meta());
            
            std::string host_wrapper = host_codegen_.generate_host_wrapper(*op, kernel_codegen_.get_kernel_meta());
            result += host_wrapper;
            result += "\n";
        }
    }
    
    return result;
}

std::string CUDACodeGenerator::generate_kernel_with_host(
    const tensorir::TensorOp& op,
    const tensorir::Schedule& schedule) {
    
    std::string result;
    result += "#include <cuda_runtime.h>\n";
    result += "#include <cuda_runtime_api.h>\n";
    result += "#include <device_launch_parameters.h>\n\n";
    
    result += kernel_codegen_.generate_kernel(op, schedule);
    result += "\n";
    result += host_codegen_.generate_host_wrapper(op, kernel_codegen_.get_kernel_meta());
    
    return result;
}

// ============================================================================
// 便捷函数
// ============================================================================

std::string generate_cuda_code(const tensorir::TensorOp& op,
                                const tensorir::Schedule& schedule,
                                const CUDACodegenConfig& config) {
    CUDACodeGenerator generator(config);
    return generator.generate_kernel_with_host(op, schedule);
}

std::string generate_cuda_launch_code(const CUDAKernelMeta& meta,
                                       const std::vector<std::string>& arg_names) {
    std::stringstream ss;
    ss << "dim3 block(" << meta.block_dim_x << ", " << meta.block_dim_y << ", " << meta.block_dim_z << ");\n";
    ss << "dim3 grid(" << meta.grid_dim_x << ", " << meta.grid_dim_y << ", " << meta.grid_dim_z << ");\n";
    
    ss << meta.kernel_name << "<<<grid, block";
    if (meta.shared_memory_size > 0) {
        ss << ", " << meta.shared_memory_size;
    }
    ss << ">>>(";
    
    for (size_t i = 0; i < arg_names.size(); ++i) {
        if (i > 0) ss << ", ";
        ss << arg_names[i];
    }
    ss << ");\n";
    ss << "cudaDeviceSynchronize();\n";
    
    return ss.str();
}

} // namespace backend
} // namespace claw
